# Site settings
author: Mark Enright
title: CLI Premier League Table
header-img: img/home-bg.png
email: enright.mark@gmail.com
copyright_name: Mark Enright
description: > # this means to ignore newlines until "baseurl:"
  Lessons learned from creating a simple CLI tool 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  markenright

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
